### ISSUE TITLE
Don't apply default config when custom config is provided

### ISSUE THREAD

**Issue by TimonVS** [TimonVS/pr-labeler-action#12]
Currently we apply the default config even when a custom config is provided (https://github.com/TimonVS/pr-labeler-action/blob/master/index.js#L6), we should probably only apply the defaults when no config is present.

Related to #11

**Comment by amacado** [comment]
good point, we should work on this.

**Comment by amacado** [comment]
i'm working on this feature as well as on #11 and #15

**Comment by TimonVS** [comment]
Nice! Thanks @amacado!

**Comment by TimonVS** [comment]
Fixed in #20 and has been released in v3.1.0.
