### ISSUE TITLE
Config is loaded from master branch not from the branch initiating the pull request

### ISSUE THREAD

**Issue by amacado** [TimonVS/pr-labeler-action#6]
When a pull request is openend i would expect the action to set the labels based on the configuration defined in `.github/pr-labeler.yml` in the state of the branch which had openened the pull request. Instead of this expected behaviour the labels are set based on the content of the file `.github/pr-labeler.yml` in the _master_ branch.

It probably can be fixed in this line:
`...(await getConfig(tools.github, CONFIG_FILENAME, repoInfo))` (https://github.com/amacado/pr-labeler-action/blob/847c751ca2554e9cf28e023bb6dcb0e667e3c47e/index.js#L22)

**Comment by TimonVS** [comment]
Good find! We should pass the current ref here: https://github.com/TimonVS/pr-labeler-action/blob/master/utils/config.js#L11 (see: https://octokit.github.io/rest.js/#octokit-routes-repos-get-contents).

**Comment by amacado** [comment]
thanks for pointing to the solution @TimonVS. I just pushed an update which solves this issue.

**Comment by TimonVS** [comment]
Fix has been merged (https://github.com/TimonVS/pr-labeler-action/pull/9)
