### ISSUE TITLE
bump release tag

### ISSUE THREAD

**Issue by tophercf** [TimonVS/pr-labeler-action#74]
hi - would you be able to bump the release tag for this action for the node16 changes? many thanks!!!

**Comment by TimonVS** [comment]
I'm on it! I want to upgrade a few dependencies first, expect a release in the coming days.

**Comment by TimonVS** [comment]
[`v4.0.0`](https://github.com/TimonVS/pr-labeler-action/releases/tag/v4.0.0) has been released now!
