### ISSUE TITLE
Getting Warning in Node version only for pr-labeler-action

### ISSUE THREAD

**Issue by vivelan** [TimonVS/pr-labeler-action#83]
Hi,

I have shifted all my Github Action(Pipeline) from 16 to 20 th version for Node, but I am facing warning only for PMD pipeline, Kindly help me to resolve this.

Pipeline code:

name: Pull Request Automations - General

on:
  [pull_request]

jobs:
  pr-automations-general:
    name: General applicable Automations for Pull Requests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    # Now we install nodejs in the VM, and specify version 14
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Label PR type
      uses: TimonVS/pr-labeler-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Label PR size
      uses: "pascalgn/size-label-action@v0.5.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        IGNORED: ".gitignore\n.coveragerc\ncore/migrations/**"
      with:
        sizes: >
          {
            "0": "XS",
            "20": "S",
            "50": "M",
            "200": "L",
            "800": "XL",
            "2000": "XXL"
          }
      continue-on-error: true

Warning:

[General applicable Automations for Pull Requests](https://github.com/vivelan/CRMIT/actions/runs/7722821258/job/21051665619)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: TimonVS/pr-labeler-action@v4, pascalgn/size-label-action@v0.5.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Thanks

**Comment by TimonVS** [comment]
Thanks for reporting! This should be fixed in v5. I also include the the build in the main branch now, so you can easily pin to a specific commit hash (e.g., `506f1ec19ca600842057ce5e242cc08de33dd869` for v5).
